services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    links:
        - db:db
    networks:
        - djangonetwork
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
        - djangonetwork

volumes:
  postgres-data:
  static-data:

networks:
    djangonetwork:
        driver: bridge